vim.g.mapleader = " "
require("plugins")
require("diagnostics")
require("options")
require("Lualine")
require("Blink")
require("Harpoon")
require("molten")
require("Gitsigns")
require("MiniComment")
require("MiniAround")
require("MiniSurround")
require("lsp")
require("floatterm")
require("Aerial")
