vim.g.mapleader = " "
require("plugins")
require("plugin_options")
require("diagnostics")
require("options")
require("Blink")
require("Harpoon")
require("molten")
require("Gitsigns")
require("MiniComment")
require("MiniAround")
require("MiniSurround")
require("MiniPairs")
require("lsp")
